<a href="https://colab.research.google.com/github/simoneminorr/DS-3001-Project/blob/main/DS3001_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS 3001 Project
*by Brittany Asare, Hewan Kasie, and Simone Minor*

In [4]:
import requests
import pandas as pd
import numpy as np

In [6]:
jobedu = pd.read_csv('highered_00001.csv')

In [7]:
jobedu.head()

PERSONID  YEAR    WEIGHT  SAMPLE  SURID  AGE  GENDER  MINRTY  \
0  10000000000000007  1993  407.6917     101      1   33       2       0   
1  10000000000000102  1993   69.2621     101      1   38       2       0   
2  10000000000000103  1993   52.3937     101      1   48       1       0   
3  10000000000000106  1993   52.3937     101      1   48       1       0   
4  10000000000000108  1993  436.3180     101      1   28       2       0   

   RACETH  CHTOT  ...  EMSEC  GOVSUP   SALARY  NRREA  NRSEC  JOBSATIS  NWLAY  \
0       2     98  ...      4     0.0    31000     98    NaN       NaN     98   
1       2      2  ...     98    98.0  9999998     98    NaN       NaN      1   
2       2     98  ...      4     0.0    48000     98    NaN       NaN     98   
3       2      2  ...      4     0.0  9999999      4    NaN       NaN     98   
4       2     98  ...      4     0.0    30000     98    NaN       NaN     98   

   NWNOND  NWOCNA  NWSTU  
0      98      98     98  
1       0       0      0  
2      98      98     98  
3      98      98     98  
4      98      98     98  

[5 rows x 31 columns]

In [8]:
jobedu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575014 entries, 0 to 575013
Data columns (total 31 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   PERSONID  575014 non-null  int64  
 1   YEAR      575014 non-null  int64  
 2   WEIGHT    575014 non-null  float64
 3   SAMPLE    575014 non-null  int64  
 4   SURID     575014 non-null  int64  
 5   AGE       575014 non-null  int64  
 6   GENDER    575014 non-null  int64  
 7   MINRTY    575014 non-null  int64  
 8   RACETH    575014 non-null  int64  
 9   CHTOT     575014 non-null  int64  
 10  NBAMED    575014 non-null  int64  
 11  DGRDG     575014 non-null  int64  
 12  NDGMED    575014 non-null  int64  
 13  NDGMEMG   575014 non-null  int64  
 14  HDRGN     418731 non-null  float64
 15  HDFLN     350876 non-null  float64
 16  SAMEFLD   89743 non-null   float64
 17  LFSTAT    575014 non-null  int64  
 18  HRSWK     292010 non-null  float64
 19  OCEDRLP   575014 non-null  int64  
 20  NOCP

In [9]:
jobedu.describe()

PERSONID           YEAR         WEIGHT         SAMPLE  \
count  5.750140e+05  575014.000000  575014.000000  575014.000000   
mean   2.791523e+16    1997.970086     156.897692     345.345842   
std    1.962432e+16       4.233752     218.310634     202.992020   
min    1.000000e+16    1993.000000       1.000000     101.000000   
25%    1.000001e+16    1995.000000      23.394300     201.000000   
50%    2.000601e+16    1997.000000      83.721650     302.000000   
75%    5.000003e+16    2003.000000     175.563300     601.000000   
max    9.090909e+16    2006.000000    5050.919300     701.000000   

               SURID            AGE         GENDER         MINRTY  \
count  575014.000000  575014.000000  575014.000000  575014.000000   
mean        1.531257      45.324634       1.673930       0.133710   
std         0.693951      12.523234       0.468774       0.340341   
min         1.000000      23.000000       1.000000       0.000000   
25%         1.000000      35.000000       1.000000       0.000000   
50%         1.000000      44.000000       2.000000       0.000000   
75%         2.000000      54.000000       2.000000       0.000000   
max         3.000000      75.000000       2.000000       1.000000   

              RACETH          CHTOT  ...          EMSEC         GOVSUP  \
count  575014.000000  575014.000000  ...  575014.000000  519116.000000   
mean        2.009325      54.440676  ...      16.067765      11.861428   
std         0.509067      47.732873  ...      32.403952      31.681318   
min         1.000000       0.000000  ...       1.000000       0.000000   
25%         2.000000       2.000000  ...       3.000000       0.000000   
50%         2.000000      98.000000  ...       4.000000       0.000000   
75%         2.000000      98.000000  ...       4.000000       1.000000   
max         4.000000      98.000000  ...      98.000000      98.000000   

             SALARY          NRREA          NRSEC       JOBSATIS  \
count  5.750140e+05  575014.000000  448293.000000  256461.000000   
mean   1.626762e+06      86.765025      87.058464      15.030975   
std    3.623297e+06      30.550908      30.402014      33.324047   
min    0.000000e+00       1.000000       0.000000       1.000000   
25%    4.000000e+04      98.000000      98.000000       1.000000   
50%    6.000000e+04      98.000000      98.000000       2.000000   
75%    1.000000e+05      98.000000      98.000000       2.000000   
max    9.999999e+06      98.000000      98.000000      98.000000   

               NWLAY         NWNOND         NWOCNA          NWSTU  
count  575014.000000  575014.000000  575014.000000  575014.000000  
mean       84.764032      84.775715      84.768000      84.772922  
std        33.480727      33.451308      33.470737      33.458344  
min         0.000000       0.000000       0.000000       0.000000  
25%        98.000000      98.000000      98.000000      98.000000  
50%        98.000000      98.000000      98.000000      98.000000  
75%        98.000000      98.000000      98.000000      98.000000  
max        98.000000      98.000000      98.000000      98.000000  

[8 rows x 31 columns]

Cleaning the missing, blank, NaN values that were coded for in NBAMED, NGDMED, HDRGN, HDFLN, HRSWK, and NRSEC and changing them into clean columns

In [11]:
jobedu['NBAMED'].value_counts()

NBAMED
226395    68349
198895    50944
799995    50135
438995    46899
547280    39603
318730    38507
587995    38320
459395    29108
567350    29091
449995    24234
338785    22788
298895    21346
537260    19610
419295    17691
527250    15821
398895    14673
611995    11632
719995    11521
999996    11327
699995     6239
429295     5981
999999     1109
489395       67
388795       19
Name: count, dtype: int64

In [10]:
jobedu['NBAMED'].unique()

array([226395, 587995, 799995, 719995, 438995, 537260, 999996, 419295,
       198895, 527250, 318730, 547280, 449995, 298895, 459395, 398895,
       567350, 338785, 388795, 489395, 999999, 429295, 699995, 611995])

In [12]:
jobedu['NBAMED_clean'] = jobedu['NBAMED'].replace({999996: np.nan, 999999: np.nan})

In [13]:
jobedu.dropna(subset=['NBAMED_clean'], inplace=True)
print('Removed values and dropped rows.')

Removed values and dropped rows.


In [14]:
jobedu['NBAMED'].unique()

array([226395, 587995, 799995, 719995, 438995, 537260, 419295, 198895,
       527250, 318730, 547280, 449995, 298895, 459395, 398895, 567350,
       338785, 388795, 489395, 429295, 699995, 611995])

In [15]:
jobedu['NDGMED'].unique()

array([799995, 587995, 719995, 438995, 226395, 537260, 419295, 198895,
       527250, 318730, 547280, 449995, 459395, 298895, 398895, 567350,
       338785, 999999, 699995, 611995, 429295])

In [16]:
jobedu['NDGMED_clean']=jobedu['NDGMED'].replace({999999: np.nan})
jobedu.dropna(subset=['NDGMED_clean'], inplace=True)
print('Removed values and dropped rows.')

Removed values and dropped rows.


In [17]:
jobedu['NDGMED'].unique()

array([799995, 587995, 719995, 438995, 226395, 537260, 419295, 198895,
       527250, 318730, 547280, 449995, 459395, 298895, 398895, 567350,
       338785, 699995, 611995, 429295])

In [18]:
jobedu['NDGMEMG'].unique()

array([7, 5, 4, 2, 1, 3, 6])

In [19]:
jobedu['NDGMEMG_clean']=jobedu['NDGMEMG'].replace({99: np.nan})
jobedu.dropna(subset=['NDGMEMG_clean'], inplace=True)
print('Removed values and dropped rows.')

Removed values and dropped rows.


In [20]:
jobedu['NDGMEMG_clean'].unique()

array([7, 5, 4, 2, 1, 3, 6])

In [21]:
jobedu['HDRGN'].unique()

array([ 2.,  1.,  7.,  3., 60.,  6.,  5.,  4.,  9.,  8., 99., nan])

In [22]:
jobedu['HDRGN_clean']=jobedu['HDRGN'].replace({99: np.nan})
jobedu.dropna(subset=['HDRGN_clean'], inplace=True)
print('Removed values and dropped rows.')

Removed values and dropped rows.


In [23]:
jobedu['HDRGN_clean'].unique()

array([ 2.,  1.,  7.,  3., 60.,  6.,  5.,  4.,  9.,  8.])

In [24]:
jobedu['HDFLN'].unique()

array([nan,  0., 99.,  1., 97., 98., 96.])

In [25]:
jobedu['HDFLN_clean']=jobedu['HDFLN'].replace({99: np.nan})
jobedu.dropna(subset=['HDFLN_clean'], inplace=True)
print('Removed values and dropped rows.')

Removed values and dropped rows.


In [26]:
jobedu['HDFLN_clean'].unique()

array([ 0.,  1., 97., 98., 96.])

In [27]:
jobedu['HRSWK'].unique()

array([nan, 40., 45., 55., 98.,  8., 60., 41., 30., 32., 50., 42., 44.,
       57., 54., 65., 36., 15., 20., 80., 10., 35., 43., 38., 39., 16.,
       28., 24., 48., 70., 47.,  2., 23., 25., 68., 18., 19., 46., 75.,
        3., 37., 14., 51., 22., 53., 11.,  5., 49., 34., 33., 52.,  6.,
       21., 12., 64.,  4., 67.,  7., 27., 29., 13., 58., 63.,  9., 72.,
       56., 17., 26.,  1., 76., 31., 66., 79., 62., 73., 69., 61., 59.,
       71., 74., 78., 77.])

In [28]:
jobedu.dropna(subset=['HRSWK'], inplace=True)
print('Dropped rows with NaN values in HRSWK column.')

Dropped rows with NaN values in HRSWK column.


In [29]:
jobedu['NRSEC'].unique()

array([ 3., 98.,  2., 96.,  1.,  6.,  4.,  5.,  7.,  0.])

In [30]:
jobedu['NRSEC_clean']=jobedu['NRSEC'].replace({96: np.nan})
jobedu.dropna(subset=['NRSEC_clean'], inplace=True)
print('Removed values and dropped rows.')

Removed values and dropped rows.


In [31]:
jobedu['NRSEC_clean'].unique()

array([ 3., 98.,  2.,  1.,  6.,  4.,  5.,  7.,  0.])

In [32]:
jobedu_clean= jobedu.dropna(how='all')

Abstract: A one paragraph summary of the question, methods, and results (about
350 words).


The current job market in the United States has undergone significant changes in recent decades, creating unique challenges for individuals seeking employment, particularly for recent college graduates suffering significantly. Our project seeks to investigate the labor market outcomes with a focus on demographic factors such as race, gender, and field of study shape opportunities and barriers in securing employment. Utilizing data from IPUMS, drawn from national surveys including the NSCG, SDR, NSRCG, and ISDR, we constructed a dataset that encompasses the decades of labor force experiences. This dataset allows us to analyze a wide range of variables, including technical skill, highest degree earned, employment status, occupation, employer characteristics, income, job characteristics, job satisfaction, and career trajectory. After cleaning and preparing our data, we applied statistical and visualization methods to identify disparities in employment access and outcomes. Our finding suggests… [TBD]

Data: One to two pages discussing the data and key variables, and any challenges in reading, cleaning, and preparing them for analysis.


- Technical Variables
- Demographic Variables
- Bachelor's Degree Variables
- Highest Degree Variables
- Employment Variables
- Occupation Variables
- Employer Characteristics Variables
- Income Variables
- Job Characteristics Variables
- Job Satisfaction Variables
- Career Path Jobs Variables



PERSONID (Individual identification number)
YEAR (Survey year)
WEIGHT (SESTAT weight)
SAMPLE (Sample identifier)
SURID (Survey identifier)
AGE (Age)
GENDER (Gender)
MINRTY (Minority indicator)
RACETH (Race/ethnicity)
CHTOT (Total number of children)
NBAMED (Field of major for first bachelor degree code)
DGRDG (Type of highest certificate or degree)
NDGMED (Field of major for highest degree )
NDGMEMG (Field of major for highest degree (major group))
HDRGN (Location of school awarding highest degree)
HDFLN (Financial support for highest degree: loans)
SAMEFLD (Likelihood of choosing same field of study for highest degree)
LFSTAT (Labor force status)
HRSWK (Principal job hours worked)
OCEDRLP (Principal job related to highest degree)
NOCPR (Job code for principal job)
EMSEC (Employer sector)
GOVSUP (Federal government support indicator)
SALARY (Salary (annualized))
NRREA (Most important reason for working outside field of highest degree)
NRSEC (Second most important reason for working outside field of highest degree)
JOBSATIS (Job satisfaction)
NWLAY (Reasons for not working: layoff)
NWNOND (Reasons for not working: did not need/want to work)
NWOCNA (Reasons for not working: suitable job not available)
NWSTU (Reasons for not working: student)

Based on our interest in the current economic state of our nation, we decided to take a dive into the current job market and the difficulties that it portrays for those who are in search of employment. We extracted our data from IPUMS and got our data from a variety of sources, including surveys from across the last few decades, such as NSCG, SDR, NSRCG, and ISDR. In doing so, we were able to get a grasp on the current state of job market. This was a single dataset that we would later be able to derive an analysis from in the ease of securing a job in today’s economy.  

The main variables that we analyzed from our dataset were the following: technical skill, demographic, highest degree achieved, employment, occupation, employer characteristics, income, job characteristics, job satisfaction, and career path jobs. These variables are essential to our research question-- what are the labor market outcomes for college graduates by major, race, and gender--  because they will better explain the reasoning as to how jobs are found, the capacity in which the job is described, and the feasibility of its accessibility to those who are in search of employment. We are also then able to cross-reference those variables with gender, race, and major of the recent graduate to analyze at which point the labor market is favorable towards certain demographic groups and what is expected from domains. The job market has become increasingly difficult to navigate, especially for new college graduates, as its requirements have become more specific. As a result, many job seekers struggle to find matching criteria that meet their needs. By identifying these variables, we are able to analyze their effects on the labor market selection and requirements, and their search results for those who are using it to find employment.

In processing this data, the issues that we ran into consisted of recoding the missing data per variable. As we know, for many datasets, there are instances where the category goes unanswered per entry or there was no information provided. In order to address these concerns, we first had to identify the areas of the variable that resulted in either NaN or missing values. We would then go on to recode this area in each variable to ensure that it was no longer a string and rather a numeric value that would then be able to be used as a point in our analysis while not skewing our data.  

Some limitations that may affect our analysis of the data are logical skipping points that were consistent through the data from the questions that respondents bypassed based on their previous responses. The “Logical Skips” are normally coded by a number, and it would be inaccurate and a misrepresentation to drop this data, but we are unsure of how it will affect the relationships we are measuring in our data.  

Methods and Results: Two to four pages providing visualizations, statistics, tables, a discussion of your methodology, and a presentation of your main results. In
particular, how are you approaching the problem? How confident are you about your
assessments?

Conclusion: One to two pages summarizing the project, defending it from criticism, and suggesting additional work that was outside the scope of the project

References: Cite the data sources and relevant works you have referenced.

Minnesota Population Center. IPUMS Higher Ed: Version 1.0 [dataset]. Minneapolis, MN: University of Minnesota, 2016. https://doi.org/10.18128/D100.V1.0

 National Survey of College Graduates 1993, SESTAT
      Survey of Doctorate Recipients 1993, SESTAT
      National Survey of Recent College Graduates 1993, SESTAT
      National Survey of College Graduates 1995, SESTAT
      Survey of Doctorate Recipients 1995, SESTAT
      National Survey of Recent College Graduates 1995, SESTAT
      National Survey of College Graduates 1997, SESTAT
      Survey of Doctorate Recipients 1997, SESTAT
      National Survey of Recent College Graduates 1997, SESTAT
      National Survey of College Graduates 1999, SESTAT
      Survey of Doctorate Recipients 1999, SESTAT
      National Survey of Recent College Graduates 1999, SESTAT
      National Survey of College Graduates 2003, SESTAT
      Survey of Doctorate Recipients 2003, SESTAT
      National Survey of Recent College Graduates 2003, SESTAT
      National Survey of College Graduates 2006, SESTAT
      Survey of Doctorate Recipients 2006, SESTAT
      National Survey of Recent College Graduates 2006, SESTAT
      National Survey of College Graduates 2008, SESTAT
      Survey of Doctorate Recipients 2008, SESTAT
      National Survey of Recent College Graduates 2008, SESTAT
      National Survey of College Graduates 2010, SESTAT
      Survey of Doctorate Recipients 2010, SESTAT
      National Survey of Recent College Graduates 2010, SESTAT
      National Survey of College Graduates 2013, SESTAT
      Survey of Doctorate Recipients 2013, SESTAT

Appendix: If you have a significant number of additional plots or tables that you feel are essential to the project, you can put any amount of extra content (after the
References section) at the end and mention it in the body of the paper. Be aware that
readers are not required to read the appendix, and that the main paper content
should stand on its own.
